## Plugins
plugins:
  - jekyll-sitemap
  - jekyll-multiple-languages-plugin
safe: false

# I18n
languages: ["ru", "en"]
# exclude_from_localizations: [
#   "img",
#   "js",
#   "fonts",
#   "css", 
#   "CNAME"
# ]
defaultLang: ru
languageNames:
  ru: Russian
  en: English

## Build Settings
markdown: kramdown
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']
sass:
  sass_dir: _sass

baseurl: ""
url: "https://geooooo.github.io"
heroImage: "city.jpg"
statisticBlockImage: "statistic.jpg"
beforeImages:
 - "before1.jpeg"
 - "before2.jpeg"
 - "before3.jpeg"
 - "before4.jpeg"
questionImage: "question.jpg"
aboutImage: "about.jpg"
