## Plugins
plugins:
 - jekyll-sitemap
 - jekyll-redirect-from
safe: false

## Build Settings
markdown: kramdown
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']
sass:
  sass_dir: _sass

## Site Settings
baseurl: ""
url: "TODO:"
siteVerification: "TODO: какой-то ключ гугла"
twitterAccount: "TODO:"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"
heroImage: "hero.jpg"
statisticBlockImage: "statistic.jpg"
beforeImages:
 - "before1.jpg"
 - "before2.jpg"
 - "before3.jpg"
 - "before4.jpg"
questionImage: "question.jpg"
aboutImage: "about.jpg"