## Plugins
plugins:
 - jekyll-sitemap
# - jekyll-redirect-from
safe: false

## Build Settings
markdown: kramdown
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']
sass:
  sass_dir: _sass

## Site Settings
title: "GDG DevFest Voronezh 2019"
baseurl: ""
url: "https://geooooo.github.io"
#siteVerification: "TODO: какой-то ключ гугла"
#twitterAccount: "TODO:"
#socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
#socialImageSrcFacebook: "/img/seo/sharing-facebook.png"
heroImage: "city.jpg"
statisticBlockImage: "statistic.jpg"
beforeImages:
 - "before1.jpeg"
 - "before2.jpeg"
 - "before3.jpeg"
 - "before4.jpeg"
questionImage: "question.jpg"
aboutImage: "about.jpg"
